const Map<String, String> appStringsVi = {
  'appName': 'Life Dashboard',
  'appTagline': 'Một App. Một Cuộc Sống.',
  'tabHome': 'Trang chủ',
  'tabStats': 'Thống kê',
  'tabCalendar': 'Lịch',
  'tabProfile': 'Cá nhân',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',
  'goodMorning': 'Chào buổi sáng',
  'goodAfternoon': 'Chào buổi chiều',
  'goodEvening': 'Chào buổi tối',
  'todayScore': 'Điểm hôm nay',
  'calendar': 'Lịch',
  'todo': 'Việc cần làm',
  'goals': 'Mục tiêu',
  'countdown': 'Đếm ngược',
  'expenses': 'Chi tiêu',
  'water': 'Uống nước',
  'sleep': 'Ngủ',
  'steps': 'Bước chân',
  'mood': 'Tâm trạng',
  'eventsToday': '{count} sự kiện hôm nay',
  'tasksCount': '{count} việc',
  'activeGoals': '{count} đang hoạt động',
  'countdownEvents': '{count} sự kiện',
  'glassesCount': '{current} / {goal} ly',
  'stepsCount': '{count}',
  'moodHappy': 'Vui vẻ',
  'today': 'Hôm nay',
  'tomorrow': 'Ngày mai',
  'upcoming': 'Sắp tới',
  'completed': 'Hoàn thành',
  'active': 'Đang hoạt động',
  'achieved': 'Đã đạt',
  'daysLeft': 'Ngày còn lại',
  'totalExpenses': 'Tổng chi tiêu',
  'recentTransactions': 'Giao dịch gần đây',
  'addEvent': 'Thêm sự kiện',
  'addTask': 'Thêm việc',
  'addGoal': 'Thêm mục tiêu',
  'addCountdown': 'Thêm đếm ngược',
  'addExpense': 'Thêm chi tiêu',
  'addWater': 'Thêm ly nước',
  'logSleep': 'Ghi nhật ký ngủ',
  'logSteps': 'Ghi bước chân',
  'logMood': 'Ghi tâm trạng',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'edit': 'Sửa',
  'title': 'Tiêu đề',
  'location': 'Địa điểm',
  'category': 'Danh mục',
  'amount': 'Số tiền',
  'date': 'Ngày',
  'time': 'Giờ',
  'lastNight': 'Đêm qua',
  'sleepQuality': 'Điểm chất lượng giấc ngủ',
  'sleepTime': 'Giờ ngủ',
  'wakeTime': 'Giờ thức',
  'distance': 'Khoảng cách',
  'calories': 'Calories',
  'activeTime': 'Thời gian hoạt động',
  'howAreYou': 'Bạn cảm thấy thế nào?',
  'veryBad': 'Rất tệ',
  'bad': 'Tệ',
  'neutral': 'Bình thường',
  'good': 'Tốt',
  'great': 'Tuyệt vời',
  'weeklyHistory': 'Lịch sử tuần',
  'noData': 'Chưa có dữ liệu',
  'emptyTasks': 'Không có việc trong ngày này',
  'emptyEvents': 'Không có sự kiện',
  'emptyGoals': 'Chưa có mục tiêu. Bắt đầu ngay!',
  'emptyCountdown': 'Chưa có đếm ngược',
  'emptyExpenses': 'Chưa ghi chi tiêu',
  'profile': 'Cá nhân',
  'myShop': 'Cửa hàng',
  'coins': 'Xu',
  'yourWallet': 'Ví của bạn',
  'dailyReward': 'Phần thưởng hàng ngày',
  'claim': 'Nhận',
  'claimed': 'Đã nhận',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại',
  'insufficientCoins': 'Không đủ xu',
  'alreadyOwned': 'Đã sở hữu',
  'coinsAdded': 'Đã thêm xu!',
  'removeAdsUnlocked': 'Đã gỡ quảng cáo!',
  'dailyRewardClaimed': 'Đã nhận thưởng hàng ngày!',
  'taskRewardEarned': 'Thưởng hoàn thành việc!',
  'goalRewardEarned': 'Thưởng cột mốc mục tiêu!',
  'streakRewardEarned': 'Thưởng chuỗi ngày!',
  'shopRemoveAds': 'Gỡ quảng cáo',
  'shopRemoveAdsDesc': 'Gỡ quảng cáo vĩnh viễn',
  'shopThemeOcean': 'Theme Đại dương',
  'shopThemeOceanDesc': 'Tông màu xanh biển mát mẻ',
  'shopThemeForest': 'Theme Rừng',
  'shopThemeForestDesc': 'Theme xanh thiên nhiên tươi mát',
  'shopThemeSunset': 'Theme Hoàng hôn',
  'shopThemeSunsetDesc': 'Màu cam ấm áp hoàng hôn',
  'shopThemeLavender': 'Theme Lavender',
  'shopThemeLavenderDesc': 'Theme tím lavender nhẹ nhàng',
  'shopBgClouds': 'Nền Mây',
  'shopBgCloudsDesc': 'Nền gradient mây mềm mại',
  'shopBgStars': 'Đêm sao',
  'shopBgStarsDesc': 'Nền không gian đêm sao',
  'shopBgRainbow': 'Nền Cầu vồng',
  'shopBgRainbowDesc': 'Gradient cầu vồng đầy màu',
  'shopBgAurora': 'Nền Cực quang',
  'shopBgAuroraDesc': 'Hiệu ứng cực quang Bắc Âu',
  'shopSkinSoft': 'Thẻ Mềm',
  'shopSkinSoftDesc': 'Kiểu thẻ bo tròn mềm mại',
  'shopSkinGlass': 'Thẻ Kính',
  'shopSkinGlassDesc': 'Hiệu ứng thẻ kính mờ',
  'shopSkinBold': 'Thẻ Đậm',
  'shopSkinBoldDesc': 'Kiểu thẻ viền đậm',
  'shopFeatExport': 'Xuất dữ liệu',
  'shopFeatExportDesc': 'Xuất toàn bộ dữ liệu dạng JSON',
  'shopFeatCountdown': 'Đếm ngược không giới hạn',
  'shopFeatCountdownDesc': 'Thêm tối đa 50 sự kiện đếm ngược',
  'shopFeatCharts': 'Biểu đồ Premium',
  'shopFeatChartsDesc': 'Biểu đồ và phân tích nâng cao',
  'shopFeatExpense': 'Chi tiêu Pro',
  'shopFeatExpenseDesc': 'Danh mục chi tiêu nâng cao',
  'shopMenuPremium': 'Premium',
  'shopMenuAll': 'Tất cả',
  'shopMenuThemes': 'Theme',
  'shopMenuBackgrounds': 'Hình nền',
  'shopMenuCards': 'Hình nền',
  'shopMenuSkins': 'Kiểu thẻ',
  'shopMenuFeatures': 'Tính năng',
  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Mở khóa theme, skin & tính năng premium',
  'shopBrowse': 'Danh mục',
  'shopEmptyCategory': 'Không có sản phẩm trong danh mục này',
  'buyWithCoins': 'Mua bằng xu',
  'buyWithMoney': 'Mua qua Google Play',
  'buyWithGooglePlay': 'Mua qua Google Play',
  'buyCoinsDesc': 'Chọn gói xu để mua',
  'dailyRewardDone': 'Đã nhận thưởng hôm nay',
  'claimDailyButton': 'Nhận +10',
  'earnStepDaily': 'Đăng nhập hàng ngày nhận xu miễn phí',
  'earnStepLogActivity': 'Hoàn thành việc',
  'earnStepLogActivityDesc': '+5 xu/việc (tối đa 20/ngày)',
  'earnStepMilestone': 'Đạt cột mốc mục tiêu',
  'earnStepMilestoneDesc': '+8 xu/cột mốc (tối đa 5/ngày)',
  'earnStepStreak': 'Giữ chuỗi ngày',
  'earnStepStreakDesc': '+15 xu cho chuỗi ngày',
  'earnStepBuy': 'Mua gói xu qua Google Play',
  'applied': 'Đã áp dụng!',
  'apply': 'Áp dụng',
  'resetToDefault': 'Đã đặt lại mặc định',
  'openingBilling': 'Đang mở Google Play...',
  'removeAdsIap': 'Gỡ quảng cáo qua Google Play',
  'configTimeout': 'Hết thời gian — dùng cài đặt đã lưu',
  'configNetworkError': 'Lỗi mạng — dùng cài đặt đã lưu',
  'owned': 'Đã sở hữu',
  'equipped': 'Đang dùng',
  'equip': 'Áp dụng',
  'resetDefault': 'Đặt lại mặc định',
  'settings': 'Cài đặt',
  'darkMode': 'Chế độ tối',
  'language': 'Ngôn ngữ',
  'userName': 'Tên của bạn',
  'privacyPolicy': 'Chính sách bảo mật',
  'about': 'Giới thiệu',
  'version': 'Phiên bản',
  'statsOverview': 'Tổng quan thống kê',
  'weeklyProgress': 'Tiến độ tuần',
  'limitReached': 'Đã đạt giới hạn. Vào Cửa hàng để mở khóa thêm.',
  'buyCoins': 'Mua xu',
  'restorePurchases': 'Khôi phục mua hàng',
  'billingDisabled': 'Mua trong app tạm thời không khả dụng',
  'networkError': 'Lỗi mạng. Dùng cài đặt đã lưu.',
  'deepSleep': 'Sâu',
  'lightSleep': 'Nông',
  'remSleep': 'REM',
  'awake': 'Thức',
  'excellent': 'Xuất sắc',
  'glasses': 'Ly',
  'ofGoal': 'trên {goal}',
  'km': 'km',
  'kcal': 'kcal',
  'hour': 'giờ',
  'hours': 'giờ',
  'min': 'phút',
  'current': 'Hiện tại',
  'target': 'Mục tiêu',
  'progress': 'Tiến độ',
  'all': 'Tất cả',
  'premium': 'Premium',
  'themes': 'Theme',
  'backgrounds': 'Hình nền',
  'skins': 'Kiểu thẻ',
  'features': 'Tính năng',
  'earnCoins': 'Kiếm xu',
  'earnCoinsDesc': 'Hoàn thành việc và mục tiêu để kiếm xu mỗi ngày',
  'privacyPolicyTitle': 'Chính sách bảo mật',
  'privacyPolicyBody': 'Life Dashboard lưu trữ toàn bộ dữ liệu cục bộ trên thiết bị của bạn. Chúng tôi không thu thập, truyền tải hay chia sẻ thông tin cá nhân với bên thứ ba. Lịch, việc cần làm, mục tiêu, chi tiêu và dữ liệu sức khỏe đều nằm trên thiết bị. Mua trong app được xử lý an toàn qua Google Play Billing. Bạn có thể xuất dữ liệu bất cứ lúc nào từ Cài đặt.',
  'yourCoins': '{count} xu',
  'coinPack': 'Gói {num}',
  'coinAmount': '{count} xu',
  'coinAmountTotal': 'Tổng {count} xu',
  'coinBonusExtra': '{base} + {bonus} thưởng!',
  'processingPurchase': 'Đang xử lý mua hàng...',
  'billingUnavailable': 'Google Play Billing không khả dụng',
  'productsNotFound': 'Sản phẩm chưa được cấu hình',
  'earnCoinsHint': 'Kiếm xu miễn phí hàng ngày hoặc mua gói để mở khóa ngay',
  'firstPurchaseTitle': 'Thưởng lần mua đầu!',
  'firstPurchaseDesc': '+{percent}% xu thêm cho lần mua đầu tiên',
  'firstPurchaseBadge': '+50% ĐẦU',
  'hotDealTitle': 'Deal tuần này',
  'hotDealDesc': 'Gói {pack}: +{percent}% thưởng (+{bonus} xu)',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'HOT NHẤT',
  'dailySpinTitle': 'Vòng quay may mắn',
  'dailySpinDesc': 'Quay miễn phí mỗi ngày — trúng tới 100 xu!',
  'spinNow': 'Quay ngay!',
  'spinning': 'Đang quay...',
  'spinComeBack': 'Quay lại vào ngày mai',
  'spinAlreadyDone': 'Đã quay hôm nay — quay lại ngày mai!',
  'spinWinTitle': 'Bạn nhận được {coins} xu!',
  'spinRewardEarned': 'Thưởng vòng quay!',
  'wantMoreCoins': 'Muốn thêm xu? Mua gói →',
  'loginStreak': 'Chuỗi {days} ngày 🔥',
  'unlockProgressTitle': 'Mở khóa {item}',
  'unlockReadyTitle': 'Sẵn sàng mở khóa {item}!',
  'coinsNeeded': 'Còn {count}',
  'coinsAddedWithBonus': 'Đã thêm xu + thưởng!',
  'homeUnlockTeaser': 'Còn {coins} xu để mở khóa {item}',
};
