const Map<String, String> appStringsEn = {
  'appName': 'Life Dashboard',
  'appTagline': 'One App. One Life.',
  'tabHome': 'Home',
  'tabStats': 'Stats',
  'tabCalendar': 'Calendar',
  'tabProfile': 'Profile',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'goodMorning': 'Good Morning',
  'goodAfternoon': 'Good Afternoon',
  'goodEvening': 'Good Evening',
  'todayScore': 'Today Score',
  'calendar': 'Calendar',
  'todo': 'Todo',
  'goals': 'Goals',
  'countdown': 'Countdown',
  'expenses': 'Expenses',
  'water': 'Water',
  'sleep': 'Sleep',
  'steps': 'Steps',
  'mood': 'Mood',
  'eventsToday': '{count} Events Today',
  'tasksCount': '{count} Tasks',
  'activeGoals': '{count} Active',
  'countdownEvents': '{count} Events',
  'glassesCount': '{current} / {goal} Glass',
  'stepsCount': '{count}',
  'moodHappy': 'Happy',
  'today': 'Today',
  'tomorrow': 'Tomorrow',
  'upcoming': 'Upcoming',
  'completed': 'Completed',
  'active': 'Active',
  'achieved': 'Achieved',
  'daysLeft': 'Days Left',
  'totalExpenses': 'Total Expenses',
  'recentTransactions': 'Recent Transactions',
  'addEvent': 'Add Event',
  'addTask': 'Add Task',
  'addGoal': 'Add Goal',
  'addCountdown': 'Add Countdown',
  'addExpense': 'Add Expense',
  'addWater': 'Add Glass',
  'logSleep': 'Log Sleep',
  'logSteps': 'Log Steps',
  'logMood': 'Log Mood',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'title': 'Title',
  'location': 'Location',
  'category': 'Category',
  'amount': 'Amount',
  'date': 'Date',
  'time': 'Time',
  'lastNight': 'Last Night',
  'sleepQuality': 'Sleep Quality Score',
  'sleepTime': 'Sleep Time',
  'wakeTime': 'Wake Time',
  'distance': 'Distance',
  'calories': 'Calories',
  'activeTime': 'Active Time',
  'howAreYou': 'How are you feeling?',
  'veryBad': 'Very Bad',
  'bad': 'Bad',
  'neutral': 'Neutral',
  'good': 'Good',
  'great': 'Great',
  'weeklyHistory': 'Weekly History',
  'noData': 'No data yet',
  'emptyTasks': 'No tasks for this day',
  'emptyEvents': 'No events scheduled',
  'emptyGoals': 'No goals yet. Start one!',
  'emptyCountdown': 'No countdowns yet',
  'emptyExpenses': 'No expenses recorded',
  'profile': 'Profile',
  'myShop': 'Shop',
  'coins': 'Coins',
  'yourWallet': 'Your Wallet',
  'dailyReward': 'Daily Reward',
  'claim': 'Claim',
  'claimed': 'Claimed',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough coins',
  'alreadyOwned': 'Already owned',
  'coinsAdded': 'Coins added!',
  'removeAdsUnlocked': 'Ads removed!',
  'dailyRewardClaimed': 'Daily reward claimed!',
  'taskRewardEarned': 'Task completed reward!',
  'goalRewardEarned': 'Goal milestone reward!',
  'streakRewardEarned': 'Streak reward!',
  'shopRemoveAds': 'Remove Ads',
  'shopRemoveAdsDesc': 'Remove all advertisements permanently',
  'shopThemeOcean': 'Ocean Theme',
  'shopThemeOceanDesc': 'Cool blue ocean vibes',
  'shopThemeForest': 'Forest Theme',
  'shopThemeForestDesc': 'Fresh green nature theme',
  'shopThemeSunset': 'Sunset Theme',
  'shopThemeSunsetDesc': 'Warm orange sunset colors',
  'shopThemeLavender': 'Lavender Theme',
  'shopThemeLavenderDesc': 'Soft purple lavender theme',
  'shopBgClouds': 'Cloud Background',
  'shopBgCloudsDesc': 'Soft cloud gradient background',
  'shopBgStars': 'Starry Night',
  'shopBgStarsDesc': 'Deep space star background',
  'shopBgRainbow': 'Rainbow Background',
  'shopBgRainbowDesc': 'Colorful rainbow gradient',
  'shopBgAurora': 'Aurora Background',
  'shopBgAuroraDesc': 'Northern lights aurora effect',
  'shopSkinSoft': 'Soft Cards',
  'shopSkinSoftDesc': 'Extra rounded soft card style',
  'shopSkinGlass': 'Glass Cards',
  'shopSkinGlassDesc': 'Frosted glass card effect',
  'shopSkinBold': 'Bold Cards',
  'shopSkinBoldDesc': 'Strong bordered card style',
  'shopFeatExport': 'Export Data',
  'shopFeatExportDesc': 'Export all your data as JSON',
  'shopFeatCountdown': 'Unlimited Countdowns',
  'shopFeatCountdownDesc': 'Add up to 50 countdown events',
  'shopFeatCharts': 'Premium Charts',
  'shopFeatChartsDesc': 'Advanced charts and analytics',
  'shopFeatExpense': 'Expense Pro',
  'shopFeatExpenseDesc': 'Advanced expense categories',
  'shopMenuPremium': 'Premium',
  'shopMenuAll': 'All',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Skins',
  'shopMenuFeatures': 'Features',
  'shopTitle': 'Shop',
  'shopSubtitle': 'Unlock themes, skins & premium features',
  'shopBrowse': 'Browse',
  'shopEmptyCategory': 'No items in this category',
  'buyWithCoins': 'Buy with Coins',
  'buyWithMoney': 'Buy with Google Play',
  'buyWithGooglePlay': 'Buy with Google Play',
  'buyCoinsDesc': 'Choose a coin pack to purchase',
  'dailyRewardDone': 'Daily reward already claimed',
  'claimDailyButton': 'Claim +10',
  'earnStepDaily': 'Log in daily for free coins',
  'earnStepLogActivity': 'Complete tasks',
  'earnStepLogActivityDesc': '+5 coins per task (max 20/day)',
  'earnStepMilestone': 'Reach goal milestones',
  'earnStepMilestoneDesc': '+8 coins per milestone (max 5/day)',
  'earnStepStreak': 'Keep your streak',
  'earnStepStreakDesc': '+15 coins for daily streak',
  'earnStepBuy': 'Purchase coin packs via Google Play',
  'applied': 'Applied!',
  'apply': 'Apply',
  'resetToDefault': 'Reset to default',
  'openingBilling': 'Opening Google Play...',
  'removeAdsIap': 'Remove ads via Google Play',
  'configTimeout': 'Config timeout — using cached settings',
  'configNetworkError': 'Network error — using cached settings',
  'owned': 'Owned',
  'equipped': 'Equipped',
  'equip': 'Equip',
  'resetDefault': 'Reset to Default',
  'settings': 'Settings',
  'darkMode': 'Dark Mode',
  'language': 'Language',
  'userName': 'Your Name',
  'privacyPolicy': 'Privacy Policy',
  'about': 'About',
  'version': 'Version',
  'statsOverview': 'Stats Overview',
  'weeklyProgress': 'Weekly Progress',
  'limitReached': 'Limit reached. Visit Shop to unlock more.',
  'buyCoins': 'Buy Coins',
  'restorePurchases': 'Restore Purchases',
  'billingDisabled': 'In-app purchases temporarily unavailable',
  'networkError': 'Network error. Using cached settings.',
  'deepSleep': 'Deep',
  'lightSleep': 'Light',
  'remSleep': 'REM',
  'awake': 'Awake',
  'excellent': 'Excellent',
  'glasses': 'Glasses',
  'ofGoal': 'of {goal}',
  'km': 'km',
  'kcal': 'kcal',
  'hour': 'hour',
  'hours': 'hours',
  'min': 'min',
  'current': 'Current',
  'target': 'Target',
  'progress': 'Progress',
  'all': 'All',
  'premium': 'Premium',
  'themes': 'Themes',
  'backgrounds': 'Backgrounds',
  'skins': 'Skins',
  'features': 'Features',
  'earnCoins': 'Earn Coins',
  'earnCoinsDesc': 'Complete tasks and goals to earn coins daily',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody': 'Life Dashboard stores all your data locally on your device. We do not collect, transmit, or share your personal information with third parties. Calendar events, todos, goals, expenses, and health tracking data remain on your device. In-app purchases are processed securely through Google Play Billing. You can export your data at any time from Settings.',
  'yourCoins': '{count} coins',
  'coinPack': 'Pack {num}',
  'coinAmount': '{count} coins',
  'coinAmountTotal': '{count} coins total',
  'coinBonusExtra': '{base} + {bonus} bonus!',
  'processingPurchase': 'Processing purchase...',
  'billingUnavailable': 'Google Play Billing unavailable',
  'productsNotFound': 'Products not configured yet',
  'earnCoinsHint': 'Earn free coins daily or buy packs for instant unlock',
  'firstPurchaseTitle': 'First Purchase Bonus!',
  'firstPurchaseDesc': '+{percent}% extra coins on your first buy',
  'firstPurchaseBadge': '+50% FIRST',
  'hotDealTitle': 'Weekly Hot Deal',
  'hotDealDesc': 'Pack {pack}: +{percent}% bonus (+{bonus} coins)',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'BEST VALUE',
  'dailySpinTitle': 'Lucky Spin',
  'dailySpinDesc': 'Free spin every day — win up to 100 coins!',
  'spinNow': 'Spin Now!',
  'spinning': 'Spinning...',
  'spinComeBack': 'Come back tomorrow',
  'spinAlreadyDone': 'Already spun today — come back tomorrow!',
  'spinWinTitle': 'You won {coins} coins!',
  'spinRewardEarned': 'Lucky spin reward!',
  'wantMoreCoins': 'Want more coins? Buy a pack →',
  'loginStreak': '{days}-day login streak 🔥',
  'unlockProgressTitle': 'Unlock {item}',
  'unlockReadyTitle': 'Ready to unlock {item}!',
  'coinsNeeded': '{count} more',
  'coinsAddedWithBonus': 'Coins + bonus added!',
  'homeUnlockTeaser': '{coins} more coins to unlock {item}',
};
